# Generated by Django 5.1.7 on 2025-03-27 19:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('houses', '0003_house_pets_allowed'),
    ]

    operations = [
        migrations.RenameField(
            model_name='house',
            old_name='adress',
            new_name='address',
        ),
    ]
