# Generated by Django 5.1.7 on 2025-04-23 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='experience_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
